Remove RebindableSyntax
Summary:
We don't use it and it breaks `stack repl --no-load` with:
```
<interactive>:1:6: error: Not in scope: ‘>>’

<interactive>:1:70: error: Not in scope: ‘>>’

<interactive>:1:135: error: Not in scope: ‘return’
```

I need this for #17

Reviewed By: simonmar

Differential Revision: D5044232

fbshipit-source-id: fce955c